# Generated by Django 5.2.4 on 2026-03-29 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_uommaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.BigIntegerField()),
                ('billdate', models.DateField()),
                ('purchase_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order_date', models.DateField(blank=True, null=True)),
                ('dc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_date', models.DateField(blank=True, null=True)),
                ('no_of_package', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('total_pcs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('totalamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('forwading_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_totamt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amtin_words', models.TextField(blank=True, null=True)),
                ('accno', models.CharField(blank=True, max_length=100, null=True)),
                ('delflag', models.CharField(default=' ', max_length=1)),
                ('deldate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.suppliermaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('hsncode', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transaction.purchaseheader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.BigIntegerField()),
                ('billdate', models.DateField()),
                ('purchase_order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_order_date', models.DateField(blank=True, null=True)),
                ('dc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('dc_date', models.DateField(blank=True, null=True)),
                ('no_of_package', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('total_pcs', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('totalamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('forwading_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_totamt', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amtin_words', models.TextField(blank=True, null=True)),
                ('accno', models.CharField(blank=True, max_length=100, null=True)),
                ('delflag', models.CharField(default=' ', max_length=1)),
                ('deldate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.customermaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('uom', models.CharField(max_length=50)),
                ('hsncode', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transaction.salesheader')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
