# Generated by Django 5.2.4 on 2026-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('credit_days', models.IntegerField(default=30)),
                ('opening_balance_cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_balance_dr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('shipping_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping_gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('mop', models.CharField(default='CASH', max_length=20)),
                ('delflag', models.CharField(default=' ', max_length=1)),
                ('deldate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='ADMIN', max_length=50)),
                ('customer_no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('credit_days', models.IntegerField(default=30)),
                ('opening_balance_cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_balance_dr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('shipping_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipping_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping_gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_number', models.CharField(max_length=50)),
                ('mop', models.CharField(default='CASH', max_length=20)),
                ('delflag', models.CharField(default=' ', max_length=1)),
                ('deldate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='ADMIN', max_length=50)),
                ('supplier_no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
