# Generated by Django 5.2.4 on 2026-03-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('gst_no', models.CharField(max_length=20, unique=True)),
                ('shipping_name', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('shipping_gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('mop', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('RTGS', 'RTGS'), ('NEFT', 'NEFT')], default='CASH', max_length=10)),
                ('state_type', models.CharField(choices=[('STATE', 'State'), ('INTERSTATE', 'Interstate')], default='STATE', max_length=15)),
                ('opening_cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_dr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ledger_name', models.CharField(default='SALES / DEFAULT', max_length=255)),
                ('batch_no', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('del_flag', models.CharField(default=' ', max_length=1)),
                ('del_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
