# Generated by Django 5.2.4 on 2026-03-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('gst_no', models.CharField(max_length=20, unique=True)),
                ('pan_no', models.CharField(blank=True, max_length=15, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_days', models.IntegerField(default=30)),
                ('opening_cr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_dr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mop', models.CharField(default='CASH', max_length=20)),
                ('batch_no', models.CharField(max_length=50)),
                ('del_flag', models.CharField(default=' ', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='ADMIN', max_length=50)),
            ],
        ),
    ]
