# Generated by Django 5.2.4 on 2026-04-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_uommaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255, unique=True)),
                ('opening_balance_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('opening_balance_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('group', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=100)),
                ('group_wise', models.CharField(max_length=100)),
                ('delflag', models.CharField(default=' ', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
