# Generated by Django 5.2.4 on 2026-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermaster',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliermaster',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
