# Generated by Django 5.2.4 on 2026-03-25 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='item_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.itemlocation'),
        ),
    ]
